In [2]:
from PIL import Image
import gymnasium as gym
import warnings
warnings.filterwarnings('ignore')
import torch

In [3]:
env = gym.make('CartPole-v0', render_mode='human')
state = env.reset()
env.render()

In [4]:
w = torch.tensor([[-0.7805,  0.9204],
        [-1.7232,  3.3317],
        [-3.8153,  4.5815],
        [-7.9563,  8.9472]])

In [5]:
state = env.reset()[0]
reward_sum = 0
is_done = False
is_break = False
num_step = 0
while not is_done and not is_break:
    state = torch.from_numpy(state).float()
    print(state)
    action = torch.argmax(torch.matmul(state, w))
    state, reward, is_done, is_break, info = env.step(action.item())
    reward_sum += reward
    
    num_step += 1
    if num_step > 1000:
        print('Много шагов {}: {}'.format(reward_sum, reward_sum))
        reward_sum = 0
        break

tensor([ 0.0089, -0.0005,  0.0454,  0.0018])
tensor([ 0.0089,  0.1939,  0.0454, -0.2763])
tensor([ 0.0127, -0.0018,  0.0399,  0.0304])
tensor([ 0.0127,  0.1927,  0.0405, -0.2495])
tensor([ 0.0166, -0.0030,  0.0355,  0.0557])
tensor([ 0.0165,  0.1916,  0.0366, -0.2256])
tensor([ 0.0203, -0.0040,  0.0321,  0.0784])
tensor([ 0.0202,  0.1907,  0.0337, -0.2040])
tensor([ 0.0241, -0.0049,  0.0296,  0.0992])
tensor([ 0.0240,  0.1898,  0.0316, -0.1840])
tensor([ 0.0278, -0.0058,  0.0279,  0.1184])
tensor([ 0.0276,  0.1889,  0.0302, -0.1653])
tensor([ 0.0314, -0.0066,  0.0269,  0.1367])
tensor([ 0.0313,  0.1881,  0.0297, -0.1473])
tensor([ 0.0350, -0.0074,  0.0267,  0.1546])
tensor([ 0.0349,  0.1873,  0.0298, -0.1296])
tensor([ 0.0386, -0.0082,  0.0272,  0.1724])
tensor([ 0.0385,  0.1865,  0.0307, -0.1116])
tensor([ 0.0422, -0.0091,  0.0284,  0.1906])
tensor([ 0.0420,  0.1856,  0.0323, -0.0930])
tensor([ 0.0457, -0.0099,  0.0304,  0.2097])
tensor([ 0.0455,  0.1847,  0.0346, -0.0732])
tensor([ 0