In [6]:
import torch

import numpy as np

In [7]:
input = torch.randn( 5, requires_grad=True)
target = torch.randn( 5)

In [8]:
input

tensor([-0.6007, -0.0166, -0.4997,  0.6033, -0.5869], requires_grad=True)

In [9]:
target

tensor([ 1.0292, -0.5664, -0.4244, -0.3117,  0.5521])

In [10]:
input2 = input.unsqueeze(1)
input2

tensor([[-0.6007],
        [-0.0166],
        [-0.4997],
        [ 0.6033],
        [-0.5869]], grad_fn=<UnsqueezeBackward0>)

In [11]:
target2 = target.unsqueeze(1)
target2

tensor([[ 1.0292],
        [-0.5664],
        [-0.4244],
        [-0.3117],
        [ 0.5521]])

In [12]:
loss = torch.nn.MSELoss()

output = loss(input, target)
output.backward()
output

tensor(1.0198, grad_fn=<MseLossBackward0>)

In [13]:
loss = torch.nn.MSELoss()

output = loss(input2, target2)
output.backward()
output

tensor(1.0198, grad_fn=<MseLossBackward0>)

In [14]:
np_input = [torch.tensor(i) for i in input]
np_input

C:\Users\v.tyumenev\AppData\Local\Temp\ipykernel_22436\241134177.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  np_input = [torch.tensor(i) for i in input]


[tensor(-0.6007),
 tensor(-0.0166),
 tensor(-0.4997),
 tensor(0.6033),
 tensor(-0.5869)]

In [15]:
loss = torch.stack(np_input)
loss

tensor([-0.6007, -0.0166, -0.4997,  0.6033, -0.5869])

In [16]:
loss.sum()

tensor(-1.1005)

In [17]:
s = 1
s_batch = np.expand_dims(s, axis=0)
s_batch

array([1])

In [25]:
input2

tensor([[-0.6007],
        [-0.0166],
        [-0.4997],
        [ 0.6033],
        [-0.5869]], grad_fn=<UnsqueezeBackward0>)

In [26]:
target2

tensor([[ 1.0292],
        [-0.5664],
        [-0.4244],
        [-0.3117],
        [ 0.5521]])

In [24]:
x = torch.concat((input2, target2), dim=-1)
x

tensor([[-0.6007,  1.0292],
        [-0.0166, -0.5664],
        [-0.4997, -0.4244],
        [ 0.6033, -0.3117],
        [-0.5869,  0.5521]], grad_fn=<CatBackward0>)

In [33]:
y = torch.cat((input, target), dim=-1)
y

tensor([-0.6007, -0.0166, -0.4997,  0.6033, -0.5869,  1.0292, -0.5664, -0.4244,
        -0.3117,  0.5521], grad_fn=<CatBackward0>)