In [1]:
import torch

import numpy as np

In [2]:
input = torch.randn( 5, requires_grad=True)
target = torch.randn( 5)

In [3]:
input

tensor([ 0.1253, -0.1155, -0.7457,  1.1521,  0.8121], requires_grad=True)

In [4]:
target

tensor([ 0.0705, -0.9313, -0.1945,  1.2957,  0.1703])

In [5]:
input2 = input.unsqueeze(1)
input2

tensor([[ 0.1253],
        [-0.1155],
        [-0.7457],
        [ 1.1521],
        [ 0.8121]], grad_fn=<UnsqueezeBackward0>)

In [6]:
target2 = target.unsqueeze(1)
target2

tensor([[ 0.0705],
        [-0.9313],
        [-0.1945],
        [ 1.2957],
        [ 0.1703]])

In [7]:
loss = torch.nn.MSELoss()

output = loss(input, target)
output.backward()
output

tensor(0.2809, grad_fn=<MseLossBackward0>)

In [8]:
loss = torch.nn.MSELoss()

output = loss(input2, target2)
output.backward()
output

tensor(0.2809, grad_fn=<MseLossBackward0>)

In [9]:
np_input = [torch.tensor(i) for i in input]
np_input

C:\Users\v.tyumenev\AppData\Local\Temp\ipykernel_13228\241134177.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  np_input = [torch.tensor(i) for i in input]


[tensor(0.1253),
 tensor(-0.1155),
 tensor(-0.7457),
 tensor(1.1521),
 tensor(0.8121)]

In [10]:
loss = torch.stack(np_input)
loss

tensor([ 0.1253, -0.1155, -0.7457,  1.1521,  0.8121])

In [11]:
loss.sum()

tensor(1.2283)

In [12]:
s = 1
s_batch = np.expand_dims(s, axis=0)
s_batch

array([1])

In [13]:
input2

tensor([[ 0.1253],
        [-0.1155],
        [-0.7457],
        [ 1.1521],
        [ 0.8121]], grad_fn=<UnsqueezeBackward0>)

In [14]:
target2

tensor([[ 0.0705],
        [-0.9313],
        [-0.1945],
        [ 1.2957],
        [ 0.1703]])

In [15]:
x = torch.concat((input2, target2), dim=-1)
x

tensor([[ 0.1253,  0.0705],
        [-0.1155, -0.9313],
        [-0.7457, -0.1945],
        [ 1.1521,  1.2957],
        [ 0.8121,  0.1703]], grad_fn=<CatBackward0>)

In [17]:
z = torch.tensor([1.])
y = torch.cat((input, z), dim=-1)
y

tensor([ 0.1253, -0.1155, -0.7457,  1.1521,  0.8121,  1.0000],
       grad_fn=<CatBackward0>)