In [52]:
import torch



In [53]:
input = torch.randn( 5, requires_grad=True)
target = torch.randn( 5)

In [54]:
input

tensor([ 2.4179,  0.3377,  1.1841, -2.0184,  1.5527], requires_grad=True)

In [55]:
target

tensor([-1.0403,  0.5923, -0.7383,  0.6902, -2.4948])

In [56]:
input2 = input.unsqueeze(1)
input2

tensor([[ 2.4179],
        [ 0.3377],
        [ 1.1841],
        [-2.0184],
        [ 1.5527]], grad_fn=<UnsqueezeBackward0>)

In [57]:
target2 = target.unsqueeze(1)
target2

tensor([[-1.0403],
        [ 0.5923],
        [-0.7383],
        [ 0.6902],
        [-2.4948]])

In [58]:
loss = torch.nn.MSELoss()

output = loss(input, target)
output.backward()
output

tensor(7.8878, grad_fn=<MseLossBackward0>)

In [59]:
loss = torch.nn.MSELoss()

output = loss(input2, target2)
output.backward()
output

tensor(7.8878, grad_fn=<MseLossBackward0>)