In [13]:
import torch

import numpy as np

In [5]:
input = torch.randn( 5, requires_grad=True)
target = torch.randn( 5)

In [6]:
input

tensor([ 0.3943, -1.2840,  0.9786,  1.0759, -1.2334], requires_grad=True)

In [7]:
target

tensor([ 0.1153,  1.4292, -0.6154, -0.0878,  1.0054])

In [8]:
input2 = input.unsqueeze(1)
input2

tensor([[ 0.3943],
        [-1.2840],
        [ 0.9786],
        [ 1.0759],
        [-1.2334]], grad_fn=<UnsqueezeBackward0>)

In [9]:
target2 = target.unsqueeze(1)
target2

tensor([[ 0.1153],
        [ 1.4292],
        [-0.6154],
        [-0.0878],
        [ 1.0054]])

In [10]:
loss = torch.nn.MSELoss()

output = loss(input, target)
output.backward()
output

tensor(3.2694, grad_fn=<MseLossBackward0>)

In [11]:
loss = torch.nn.MSELoss()

output = loss(input2, target2)
output.backward()
output

tensor(3.2694, grad_fn=<MseLossBackward0>)

In [17]:
np_input = [torch.tensor(i) for i in input]
np_input

C:\Users\v.tyumenev\AppData\Local\Temp\ipykernel_19908\241134177.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  np_input = [torch.tensor(i) for i in input]


[tensor(0.3943),
 tensor(-1.2840),
 tensor(0.9786),
 tensor(1.0759),
 tensor(-1.2334)]

In [21]:
loss = torch.stack(np_input)
loss

tensor([ 0.3943, -1.2840,  0.9786,  1.0759, -1.2334])

In [22]:
loss.sum()

tensor(-0.0686)

In [24]:
s = 1
s_batch = np.expand_dims(s, axis=0)
s_batch

array([1])